# frozen_string_literal: true

require_relative 'models/mixins'
require_relative 'models/model'
require_relative 'models/clouds'
require_relative 'models/coord'
require_relative 'models/main'
require_relative 'models/sys'
require_relative 'models/weather'
require_relative 'models/wind'
require_relative 'models/rain'
require_relative 'models/snow'
require_relative 'models/list'
require_relative 'models/city'
require_relative 'models/one_call'
require_relative 'models/station'
require_relative 'models/stations/measurement'
